
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  username: <%= ENV['POSTGRES_DBUSER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: talk_to_the_book_development
 
test:
  <<: *default
  database: talk_to_the_book_test

production:
  <<: *default
  database: talk_to_the_book_production
  username: talk_to_the_book
  password: <%= ENV["TALK_TO_THE_BOOK_DATABASE_PASSWORD"] %>
